services:
  - type: web
    name: devops-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run Home.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: STREAMLIT_SERVER_PORT
        value: 8501
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
