[server]
port = 10000
address = "127.0.0.1"
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
serverAddress = "127.0.0.1"
serverPort = 10000
gatherUsageStats = false

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
