[server]
port = 10000
address = "0.0.0.0"
headless = true

[browser]
serverAddress = "0.0.0.0"
serverPort = 10000

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
