# Azure OpenAI credentials
AZURE_OPENAI_KEY = "7QGuH23QnXmWgtwAHqIDEXZeripRjHYoPsALlGqynAZSx1BAOpLAJQQJ99BAACHYHv6XJ3w3AAAAACOGHFs8"
AZURE_OPENAI_ENDPOINT = "https://ai-gaharwarmilind4457ai495236228258.openai.azure.com/"
AZURE_OPENAI_API_VERSION = "2024-12-01-preview"
